name: 'dbt_package'
version: '1.0.0'
config-version: 2

profile: 'dbt_package'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

require-dbt-version: [">=1.10.0", "<1.11.0"]

models:
  dbt_package:
    +materialized: view
